// lib/swarmnet/agents/documenter.ts
// DocumenterBot — writes comments, updates descriptions, and logs timeline activities

import { createComment, createActivity, updateTicket } from '@/lib/db';

interface DocumenterContext {
  ticketId: string;
  projectId: string;
  runId: string;
  agentId: string;
  orgId: string;
}

/**
 * Post a comment on the ticket with a nice agent signature
 */
export async function postTicketComment(
  ctx: DocumenterContext,
  message: string,
  opts?: { icon?: string }
): Promise<void> {
  const icon = opts?.icon ?? '🤖';
  const content = `${icon} **DocumenterBot** — *${new Date().toLocaleString()}*\n\n${message}`;
  try {
    await createComment({
      ticket_id: ctx.ticketId,
      project_id: ctx.projectId,
      user_id: ctx.agentId,
      content,
    });
  } catch (e) {
    console.error(`[DocumenterBot ${ctx.runId}] Failed to post comment:`, e);
  }
}

/**
 * Log an activity entry on the ticket timeline
 */
export async function logTicketActivity(
  ctx: DocumenterContext,
  actionType: string,
  metadata: Record<string, unknown>
): Promise<void> {
  try {
    await createActivity({
      ticket_id: ctx.ticketId,
      user_id: ctx.agentId,
      action_type: actionType,
      metadata: {
        ...metadata,
        runId: ctx.runId,
        agentId: ctx.agentId,
        timestamp: new Date().toISOString(),
      },
    });
  } catch (e) {
    console.error(`[DocumenterBot ${ctx.runId}] Failed to log activity:`, e);
  }
}

/**
 * Update the ticket description with an implementation summary
 */
export async function appendImplementationSummary(
  ctx: DocumenterContext,
  summary: string,
  files: string[],
  branchName: string
): Promise<void> {
  const section = `

---

📋 **Implementation Summary** *(auto-generated by DocumenterBot)*

${summary}

**Files touched:**
${files.map((f) => `- \`${f}\``).join('\n')}

**Branch:** \`${branchName}\`
`;
  try {
    // We read first, then append — but updateTicket only takes partial updates.
    // We'll append a comment instead to avoid overwriting user content.
    await postTicketComment(ctx, section, { icon: '📋' });
  } catch (e) {
    console.error(`[DocumenterBot ${ctx.runId}] Failed to append summary:`, e);
  }
}

/**
 * Document a completed agent run — comments, activity, and summary
 */
export async function documentRunComplete(
  ctx: DocumenterContext,
  result: {
    success: boolean;
    prNumber?: number;
    prUrl?: string;
    branchName: string;
    filesCreated: string[];
    filesModified: string[];
    steps: { phase: string; message: string }[];
    error?: string;
  }
): Promise<void> {
  // 1. Log timeline activity
  await logTicketActivity(ctx, result.success ? 'agent_run_complete' : 'agent_run_failed', {
    runId: ctx.runId,
    prNumber: result.prNumber,
    prUrl: result.prUrl,
    branchName: result.branchName,
    filesCreated: result.filesCreated,
    filesModified: result.filesModified,
    error: result.error ?? null,
  });

  // 2. Post success / failure comment
  if (result.success) {
    const msg = [
      '✅ **Agent run complete**',
      '',
      `**PR:** [#${result.prNumber}](${result.prUrl})`,
      `**Branch:** \`${result.branchName}\``,
      '',
      '**Files created:**',
      ...result.filesCreated.map((f) => `- \`${f}\``),
      result.filesModified.length > 0 ? '' : '',
      ...(result.filesModified.length > 0
        ? ['**Files modified:**', ...result.filesModified.map((f) => `- \`${f}\``)]
        : []),
    ].join('\n');
    await postTicketComment(ctx, msg, { icon: '✅' });
  } else {
    const msg = [
      '❌ **Agent run failed**',
      '',
      `**Error:** ${result.error}`,
      `**Branch:** \`${result.branchName}\``,
      '',
      '**Phases completed before failure:**',
      ...result.steps.map((s) => `- ${s.phase}: ${s.message}`),
    ].join('\n');
    await postTicketComment(ctx, msg, { icon: '❌' });
  }

  // 3. If successful, update ticket status and append summary to description
  if (result.success) {
    try {
      await updateTicket(ctx.ticketId, { status: 'done' });
    } catch (e) {
      console.error(`[DocumenterBot ${ctx.runId}] Failed to mark ticket done:`, e);
    }

    await appendImplementationSummary(
      ctx,
      `FrontendAgent implemented this ticket in PR #${result.prNumber}.`,
      [...result.filesCreated, ...result.filesModified],
      result.branchName
    );
  }
}

/**
 * Document a single phase milestone
 */
export async function documentPhaseMilestone(
  ctx: DocumenterContext,
  phase: string,
  detail: string,
  metadata?: Record<string, unknown>
): Promise<void> {
  await logTicketActivity(ctx, `agent_phase_${phase}`, {
    phase,
    detail,
    ...metadata,
  });

  // Only comment on major milestones to avoid noise
  const majorPhases = ['plan', 'generate', 'execute', 'done', 'error'];
  if (majorPhases.includes(phase)) {
    const emoji = phase === 'done' ? '✅' : phase === 'error' ? '❌' : '🔄';
    await postTicketComment(ctx, `**Phase: ${phase}** — ${detail}`, { icon: emoji });
  }
}
